"""Tests for agent.types Plan, Step, and ExecutionResult."""

from agent.types import Clarification, ExecutionResult, Plan, Step


def _sample_plan() -> Plan:
    return Plan(
        query="Analyze TP53",
        steps=[
            Step(id=1, description="Fetch target", tool="target.druggability", status="completed"),
            Step(
                id=2,
                description="Expression profile",
                tool="target.expression",
                depends_on=[1],
                status="pending",
            ),
            Step(
                id=3,
                description="Safety screen",
                tool="safety.classify",
                depends_on=[1],
                status="pending",
            ),
        ],
    )


class TestPlan:
    def test_pending_steps(self):
        plan = _sample_plan()
        pending = plan.pending_steps()
        assert len(pending) == 2
        assert all(s.status == "pending" for s in pending)

    def test_ready_steps_respects_dependencies(self):
        plan = _sample_plan()
        ready = plan.ready_steps()
        assert len(ready) == 2
        assert {s.id for s in ready} == {2, 3}

    def test_ready_steps_empty_when_deps_incomplete(self):
        plan = Plan(
            query="q",
            steps=[
                Step(id=1, description="a", tool="t.a", status="running"),
                Step(id=2, description="b", tool="t.b", depends_on=[1], status="pending"),
            ],
        )
        assert plan.ready_steps() == []

    def test_is_complete(self):
        plan = _sample_plan()
        assert not plan.is_complete()
        for step in plan.steps:
            step.status = "completed"
        assert plan.is_complete()

    def test_summary_includes_icons(self):
        plan = _sample_plan()
        text = plan.summary()
        assert "Analyze TP53" in text
        assert "target.druggability" in text
        assert "(after [1])" in text


class TestClarification:
    def test_dataclass_fields(self):
        clar = Clarification(
            question="Which cell line?",
            missing=["cell_line"],
            suggestions=["A549", "MCF7"],
        )
        assert clar.question == "Which cell line?"
        assert clar.missing == ["cell_line"]


class TestExecutionResult:
    def test_metadata_header_and_scorecard(self):
        plan = _sample_plan()
        plan.steps[0].result = {
            "summary": "Druggable kinase",
            "data_sources": ["chembl"],
        }
        result = ExecutionResult(
            plan=plan,
            summary="TP53 is druggable.",
            duration_s=12.5,
            metadata={
                "query": "Analyze TP53",
                "timestamp": "2026-01-01",
                "model": "claude-test",
                "execution_time_s": 12.5,
                "tool_success_rate": "1/1",
                "profile": "default",
                "ct_version": "0.0.51",
                "confidence_tier": "high",
                "grounding_result": "passed",
            },
        )
        md = result.to_markdown()
        assert "Research Report: Analyze TP53" in md
        assert "Generated by fastfold-agent-cli" in md
        assert "Quality Scorecard" in md
        assert "target.druggability" in md
        assert "chembl" in md
        assert "Confidence Tier" in md

    def test_to_markdown_without_metadata(self):
        plan = Plan(query="Simple query", steps=[])
        result = ExecutionResult(plan=plan, summary="Done.")
        md = result.to_markdown()
        assert "Simple query" in md
        assert "Quality Scorecard" not in md
