"""
Ghost-text suggestions for the ct interactive terminal.

500 diverse research queries spanning every domain ct supports:
target validation, genetics, chemistry, safety, clinical, omics,
structure, networks, repurposing, biomarkers, experimental design, etc.

Shuffled at session start so every session feels different.
"""

DEFAULT_SUGGESTIONS = [
    # ── Target validation & genetic evidence ──────────────────────
    "what are the most genetically supported targets for AML?",
    "is TP53 a viable drug target? check safety, selectivity, and literature",
    "what are the co-essential partners of BRAF in melanoma?",
    "which cancer types show the strongest BRCA1 dependency?",
    "find GWAS evidence linking JAK2 to myeloproliferative diseases",
    "what's the genetic evidence for PCSK9 as a cardiovascular target?",
    "run Mendelian randomization for IL-6 in rheumatoid arthritis",
    "which transcription factors drive EMT in pancreatic cancer?",
    "validate KRAS as a target — GWAS, eQTL, and DepMap evidence",
    "what genes are co-essential with CDK4 across all cancer types?",
    "is PTPN22 a good target for autoimmune diseases? check genetic evidence",
    "find the top 10 genetically validated targets for type 2 diabetes",
    "what's the druggability score for the STING pathway?",
    "which kinases have the strongest dependency in glioblastoma?",
    "assess USP7 as a therapeutic target — expression, dependency, safety",
    "what targets are synthetically lethal with SMAD4 loss?",
    "find genetically supported targets for Crohn's disease",
    "is RIPK1 a good target for neuroinflammation?",
    "which GPCRs show tumor-specific overexpression?",
    "evaluate EZH2 as a target in diffuse large B-cell lymphoma",
    "what's the dependency profile of WRN in MSI-high tumors?",
    "find top essential genes in triple-negative breast cancer cell lines",
    "assess the target tractability of TYK2 for psoriasis",
    "which ubiquitin ligases are overexpressed in hepatocellular carcinoma?",
    "is DDR1 a viable target in pancreatic ductal adenocarcinoma?",
    "what are the top CRISPR dependencies in multiple myeloma?",
    "evaluate METTL3 as an epigenetic target in AML",
    "find targets with strong Mendelian randomization evidence for lupus",
    "which deubiquitinases are essential in colorectal cancer?",
    "assess KAT6A as an oncology target — expression and dependency data",
    "what targets emerge from GWAS for atopic dermatitis?",
    "is CD47 a safe target? check expression across normal tissues",
    "find co-essential gene pairs for MYC in neuroblastoma",
    "validate PRMT5 as a target in glioma — dependency, expression, safety",
    "which phosphatases are essential in prostate cancer?",
    "what's the genetic evidence linking LRRK2 to Parkinson's disease?",
    "evaluate SHP2 (PTPN11) as a target in RAS-driven cancers",
    "find the strongest genetic associations for inflammatory bowel disease targets",
    "is GLS1 a good target in renal cell carcinoma?",
    "assess the druggability of the Hippo pathway component YAP1",

    # ── Chemistry & compound profiling ────────────────────────────
    "find structurally similar compounds to imatinib and compare SAR",
    "suggest modifications to improve the selectivity of sotorasib",
    "what's the ADMET profile of lenalidomide?",
    "scaffold hop from erlotinib — find novel EGFR chemotypes",
    "compare molecular descriptors of approved PROTAC degraders",
    "run retrosynthesis for a bespoke KRASG12C covalent inhibitor",
    "find all approved drugs with a benzimidazole scaffold",
    "what's the SAR around the pyrimidine core of dabrafenib?",
    "compare physicochemical properties of SGLT2 inhibitors",
    "search ChEMBL for JAK1-selective compounds with IC50 < 10 nM",
    "find matched molecular pairs for improving the solubility of sorafenib",
    "what's the pharmacophore model for CDK4/6 inhibitors?",
    "profile the chemical space of FDA-approved kinase inhibitors",
    "suggest linker modifications for a BRD4-targeting PROTAC",
    "compare the selectivity profiles of BTK inhibitors ibrutinib vs acalabrutinib",
    "find PubChem compounds similar to olaparib with better oral bioavailability",
    "what molecular features distinguish PDE4 vs PDE5 inhibitors?",
    "analyze the SAR of HDAC inhibitors — what drives class selectivity?",
    "run retrosynthesis planning for a novel STING agonist scaffold",
    "find compounds in ChEMBL active against IDH1 R132H mutant",
    "compare molecular descriptors of approved GLP-1 receptor agonist small molecules",
    "what structural modifications improve blood-brain barrier penetration?",
    "scaffold hop from venetoclax — find alternative BCL-2 chemotypes",
    "search for covalent warheads suitable for targeting KRASG12C",
    "what's the chemical diversity of approved proteasome inhibitors?",
    "find bioisosteric replacements for the morpholine group in PI3K inhibitors",
    "compare the 3D shape similarity of MEK inhibitors",
    "what functional groups drive hERG channel liability?",
    "profile the lead-likeness of top hits from a recent VEGFR2 screen",
    "find molecular glue degraders similar to thalidomide in ChEMBL",
    "analyze structure-activity for Aurora kinase inhibitors",
    "what's the optimal logP range for CNS-penetrant compounds?",
    "compare the fragment hits from FBDD campaigns against BRD4",
    "suggest prodrug strategies to improve oral absorption of remdesivir",
    "find all approved drugs containing a fluorinated aromatic ring",
    "profile the chemical space of macrocyclic peptide drugs",
    "what structural alerts should I watch for in an FGFR inhibitor program?",
    "find ChEMBL compounds selective for CDK9 over CDK2",
    "analyze the SAR around the indole core of sunitinib",
    "compare approved ALK inhibitors — selectivity, potency, resistance profiles",

    # ── Synergy & combinations ────────────────────────────────────
    "find synergy partners for venetoclax in acute myeloid leukemia",
    "predict synthetic lethality partners for ARID1A-mutant tumors",
    "which compounds synergize with PARP inhibitors in BRCA-wild-type?",
    "find combination partners for anti-PD-1 therapy in melanoma",
    "predict synergy between trametinib and a CDK4/6 inhibitor in KRAS-mutant NSCLC",
    "which metabolic vulnerabilities are exposed by MYC amplification?",
    "find synthetic lethal interactions with PTEN loss in prostate cancer",
    "predict combination synergy for osimertinib + MET inhibitor",
    "which epigenetic drugs synergize with immune checkpoint inhibitors?",
    "find combination partners for BET inhibitors in diffuse large B-cell lymphoma",
    "predict synthetic lethality partners for CDKN2A-deleted tumors",
    "which drugs synergize with azacitidine in myelodysplastic syndromes?",
    "find metabolic combination opportunities in IDH1-mutant glioma",
    "predict synergy for a KRASG12C inhibitor + SHP2 inhibitor combination",
    "which compounds enhance sensitivity to cisplatin in ovarian cancer?",
    "find synthetic lethal partners for STK11/LKB1 loss in lung cancer",
    "predict the best combination partner for an FGFR inhibitor in bladder cancer",
    "which drugs overcome resistance to venetoclax in CLL?",
    "find synergy between HDAC inhibitors and proteasome inhibitors in myeloma",
    "predict combination opportunities for targeting the DDR pathway in BRCA-mutant tumors",

    # ── Clinical & competitive intelligence ───────────────────────
    "compare dose-response of doxorubicin across breast vs lung cell lines",
    "which kinase inhibitors show the best therapeutic window in solid tumors?",
    "search PubMed for KRAS G12C inhibitors in clinical trials",
    "what's the competitive landscape for GLP-1 receptor agonists?",
    "estimate patient population for FGFR2 fusion cholangiocarcinoma",
    "find clinical trials testing bispecific antibodies in solid tumors",
    "what's the clinical pipeline for TEAD inhibitors?",
    "estimate patient stratification for BRCA1/2-mutant ovarian cancer",
    "find clinical trials for CLDN18.2-targeting agents in gastric cancer",
    "what's the competitive landscape for anti-TIGIT antibodies?",
    "compare approved CDK4/6 inhibitors — efficacy, toxicity, market share",
    "estimate the addressable population for NTRK fusion-positive cancers",
    "find Phase III trials for ADCs in breast cancer",
    "what's the clinical development status of KRAS inhibitors?",
    "compare therapeutic windows of taxanes across solid tumor types",
    "search for clinical trials combining immunotherapy + TKIs in RCC",
    "what's the latest competitive landscape for NASH/MASH therapies?",
    "estimate patient population for HER2-low breast cancer",
    "find clinical trials testing CAR-T cells in solid tumors",
    "what drugs are in clinical development for sickle cell disease?",
    "compare the clinical efficacy of JAK inhibitors in atopic dermatitis",
    "what's the competitive landscape for oral PCSK9 inhibitors?",
    "find Phase II+ trials for degraders/PROTACs in oncology",
    "estimate the addressable market for EGFR exon 20 insertion mutations",
    "what's the clinical pipeline for tau-targeting therapies in Alzheimer's?",
    "compare dose-response curves for VEGFR inhibitors in renal cell lines",
    "find trials testing combination of PARP inhibitor + anti-PD-L1",
    "what's the competitive landscape for bispecific T-cell engagers?",
    "estimate patient stratification for MSI-high solid tumors",
    "search for clinical trials using CRISPR-based therapies",

    # ── Safety & off-target ───────────────────────────────────────
    "profile the safety and off-target risks of CDK4/6 inhibitors",
    "what mutations confer resistance to EGFR inhibitors?",
    "check SALL4 degradation risk for new thalidomide analogs",
    "predict drug-drug interactions for venetoclax + azacitidine",
    "what's the antitarget profile of a pan-BET inhibitor?",
    "predict ADMET properties for a novel STING agonist",
    "which off-targets should I worry about for a CDK9 inhibitor?",
    "assess hERG liability of approved kinase inhibitors",
    "what's the safety profile of HDAC inhibitors in the clinic?",
    "predict hepatotoxicity risk for a novel FGFR inhibitor scaffold",
    "what are common resistance mechanisms to ALK inhibitors?",
    "check if my compound series has PAINS structural alerts",
    "profile the safety margins of approved BTK inhibitors",
    "predict potential DDIs for an oral SERD in breast cancer",
    "what off-target kinases does dasatinib hit?",
    "assess the cardiovascular safety of JAK inhibitors",
    "what resistance mutations emerge under osimertinib treatment?",
    "predict CYP3A4 inhibition potential for a macrocyclic compound",
    "what's the therapeutic index of doxorubicin across tissue types?",
    "find known idiosyncratic toxicities of approved proteasome inhibitors",
    "check for neosubstrate degradation risk with a cereblon-binding compound",
    "predict genotoxicity flags for a novel covalent inhibitor",
    "what safety signals emerged in post-marketing for checkpoint inhibitors?",
    "assess the renal toxicity potential of a platinum-based analog",
    "predict DDI risk for combining a CYP2D6 substrate with fluoxetine",

    # ── Omics & expression ────────────────────────────────────────
    "run pathway enrichment on MYC-dependent gene expression signatures",
    "find single-cell datasets for tumor-infiltrating lymphocytes",
    "what genes are differentially expressed in KRAS-mutant vs wild-type NSCLC?",
    "search GEO for RNA-seq datasets in Alzheimer's disease",
    "deconvolve immune cell types from TCGA breast cancer bulk RNA-seq",
    "find L1000 signatures most similar to CDK4/6 inhibitor treatment",
    "what pathways are enriched in MYC-amplified neuroblastoma?",
    "search CellxGene for single-cell atlases of human liver",
    "run differential expression analysis for TP53-mutant vs wild-type AML",
    "find transcription factor activity signatures in EMT",
    "what immune subtypes exist in TCGA melanoma samples?",
    "search GEO for ATAC-seq datasets in hematopoietic stem cells",
    "find gene expression signatures that predict response to immunotherapy",
    "analyze pathway enrichment for genes co-expressed with VEGFA",
    "deconvolve tumor microenvironment from TCGA pancreatic cancer data",
    "find L1000 compounds that reverse an inflammatory gene signature",
    "search CellxGene for single-cell data on human kidney organoids",
    "what genes are upregulated in drug-resistant melanoma?",
    "run immune scoring on TCGA lung adenocarcinoma cohort",
    "find methylation differences between normal and tumor colon tissue",
    "search for proteomics datasets comparing primary vs metastatic tumors",
    "analyze chromatin accessibility in T-cell exhaustion",
    "find spatial transcriptomics datasets for human brain tumors",
    "what gene sets are enriched in oxidative phosphorylation-dependent cancers?",
    "search GEO for ChIP-seq data on EZH2 in lymphoma",
    "deconvolve cell types from bulk RNA-seq of rheumatoid arthritis synovium",
    "find datasets profiling response to CAR-T cell therapy",
    "run pathway enrichment on genes differentially methylated in glioblastoma",
    "search for multi-omics integration datasets in breast cancer",
    "what expression patterns distinguish luminal A from luminal B breast cancer?",

    # ── Structure & docking ───────────────────────────────────────
    "fetch the AlphaFold structure for human NLRP3 and find binding sites",
    "dock metformin into the AMPK binding pocket",
    "predict ternary complex for a VHL-based PROTAC targeting BRD4",
    "find allosteric binding sites on KRASG12C from PDB structures",
    "fetch the crystal structure of EGFR T790M and map resistance mutations",
    "dock a novel compound into the CDK2 ATP binding site",
    "predict binding mode for a STING agonist in the ligand pocket",
    "find PDB structures for ROR-gamma with bound inverse agonists",
    "compare binding sites of CDK4 vs CDK6 for selective inhibitor design",
    "fetch the AlphaFold structure for GPR75 and identify druggable pockets",
    "dock ibrutinib into the BTK active site and identify key interactions",
    "predict the ternary complex for a CRBN-based PROTAC targeting GSPT1",
    "find co-crystal structures of BRD4 with different chemotypes",
    "map the binding site residues of PCSK9 that interact with LDLR",
    "compare the pocket volumes of different GPCR family members",
    "fetch the cryo-EM structure of the CFTR channel",
    "identify cryptic binding sites on the surface of IL-17A",
    "dock osimertinib into EGFR C797S mutant — does it still bind?",
    "find PDB structures for PRMT5 and identify substrate binding pockets",
    "predict binding pose of a molecular glue in the CRBN-substrate interface",

    # ── Protein & network analysis ────────────────────────────────
    "what are the protein-protein interaction partners of p53?",
    "map the pathway crosstalk between PI3K/AKT and MAPK signaling",
    "annotate functional domains of the CFTR protein",
    "find all proteins that interact with MDM2 in the STRING network",
    "map the EGFR signaling network and identify key nodes",
    "annotate the domain architecture of the BRCA1 protein",
    "what proteins form a complex with SMAD4?",
    "find pathway crosstalk between WNT and Notch signaling",
    "compute ESM-2 embeddings for KRAS wild-type and G12C mutant",
    "identify hub proteins in the DNA damage response network",
    "map the interactome of the PRC2 complex",
    "what are the functional domains of ALK and where do resistance mutations cluster?",
    "find all known substrates of the CRL4-CRBN E3 ligase complex",
    "analyze the protein interaction network around NF-kB signaling",
    "compute protein embeddings to find functional analogs of BCL-2",
    "what proteins interact with both p53 and MDM4?",
    "map the ubiquitin-proteasome pathway network in cancer",
    "identify regulatory nodes in the mTOR signaling pathway",
    "annotate post-translational modifications on the histone H3 protein",
    "find the protein-protein interaction interface of PD-1 and PD-L1",

    # ── Repurposing & literature ──────────────────────────────────
    "find drug repurposing candidates for inflammatory bowel disease",
    "search recent patents on PD-L1 small molecule inhibitors",
    "what does the literature say about senolytics in idiopathic pulmonary fibrosis?",
    "find CMap connections for repurposing approved drugs to AML",
    "search PubMed for CRISPR screens identifying new cancer dependencies",
    "what are the latest repurposing hypotheses for metformin in cancer?",
    "find patent filings for molecular glue degraders in the last 2 years",
    "search OpenAlex for review articles on targeted protein degradation",
    "what approved drugs could be repurposed for Huntington's disease?",
    "find publications on resistance to KRASG12C inhibitors",
    "search PubMed for AI-driven drug discovery success stories",
    "find CMap compounds that mimic the effect of PTEN restoration",
    "search patent landscape for ADC linker-payload innovations",
    "what does the literature say about ferroptosis as a cancer vulnerability?",
    "find repurposing candidates for rare pediatric cancers",
    "search PubMed for papers linking gut microbiome to drug response",
    "find recent reviews on PROTAC clinical development",
    "what approved drugs show activity in senolytic screens?",
    "search OpenAlex for publications on spatial transcriptomics methods",
    "find patent filings for bispecific antibodies in immuno-oncology",
    "what does the literature say about epigenetic therapy in MDS?",
    "search for recent publications on CRISPR base editing therapeutics",
    "find CMap signatures that reverse an Alzheimer's disease gene program",
    "search PubMed for resistance mechanisms to ADCs",
    "what repurposing opportunities exist for statins in oncology?",

    # ── Biomarkers & patient stratification ───────────────────────
    "which mutations predict sensitivity to osimertinib?",
    "design a biomarker panel for early-stage hepatocellular carcinoma",
    "what biomarkers predict response to anti-PD-1 therapy?",
    "find resistance biomarkers for FGFR inhibitors in bladder cancer",
    "design a companion diagnostic panel for CDK4/6 inhibitor therapy",
    "which genomic alterations predict sensitivity to PARP inhibitors?",
    "find biomarkers that distinguish MDS from de novo AML",
    "what's the optimal biomarker strategy for a KRASG12C inhibitor trial?",
    "identify pharmacodynamic biomarkers for EZH2 inhibitor treatment",
    "which mutations predict resistance to second-generation ALK inhibitors?",
    "design a liquid biopsy panel for monitoring EGFR-mutant NSCLC",
    "find predictive biomarkers for venetoclax response in AML",
    "what gene expression signatures predict platinum sensitivity in ovarian cancer?",
    "identify biomarkers for patient selection in anti-TIGIT trials",
    "which copy number alterations predict response to PI3K inhibitors?",
    "design a mutation panel for hereditary cancer predisposition screening",
    "find biomarkers that predict cardiotoxicity from anthracycline treatment",
    "what biomarkers stratify responders vs non-responders to CAR-T therapy?",
    "identify early response biomarkers for BET inhibitor treatment",
    "which immune markers predict benefit from combination immunotherapy?",

    # ── Experimental design & CRO ─────────────────────────────────
    "design a CRO assay to test CDK9 inhibitor selectivity",
    "estimate timeline and cost for a 384-well high-throughput screen",
    "design a selectivity panel for a novel kinase inhibitor",
    "what's the best assay format to measure PROTAC-induced degradation?",
    "estimate costs for outsourcing an in vivo PK study in mice",
    "design a cell viability assay panel for a CDK2 inhibitor",
    "find CROs that offer CRISPR screening services",
    "design a dose-response experiment for combination synergy testing",
    "what assay would best measure target engagement for a STING agonist?",
    "estimate timeline for a lead optimization campaign with medicinal chemistry CRO",
    "design an ADME study package for a preclinical candidate",
    "what's the right assay cascade for an allosteric kinase inhibitor program?",
    "find CROs that offer organoid-based drug sensitivity testing",
    "design a biomarker validation study for a companion diagnostic",
    "estimate cost for a 1000-compound diversity screen against a novel target",
    "what animal models are most relevant for testing NASH therapeutics?",
    "design an ex vivo assay to test immune cell killing with a bispecific",
    "find CROs specializing in CNS drug delivery assessment",
    "design a screening cascade for a GPCR agonist program",
    "estimate timeline for IND-enabling studies for a small molecule",

    # ── Genomics & variants ───────────────────────────────────────
    "find GWAS loci associated with response to statin therapy",
    "annotate the functional impact of BRAF V600E mutation",
    "what eQTLs regulate expression of IL6 in immune cells?",
    "find colocalization evidence between GWAS hits and eQTLs for SLE",
    "annotate all known pathogenic variants in the BRCA2 gene",
    "what pharmacogenomic variants affect warfarin metabolism?",
    "find GWAS associations for drug-induced liver injury",
    "run variant annotation for EGFR L858R — clinical significance and frequency",
    "what are the most common somatic mutations in cholangiocarcinoma?",
    "find eQTL data linking genetic variants to FTO expression",
    "annotate the functional domains affected by TP53 hotspot mutations",
    "what GWAS loci are shared between Alzheimer's and cardiovascular disease?",
    "find rare variants in PCSK9 associated with low LDL cholesterol",
    "run Mendelian randomization for adiponectin levels and diabetes risk",
    "what somatic mutations are enriched in platinum-resistant ovarian cancer?",
    "annotate the splice variants of the androgen receptor in prostate cancer",
    "find GWAS evidence for drug targets in major depressive disorder",
    "what's the allele frequency of DPYD variants relevant to 5-FU toxicity?",
    "find colocalization between IBD GWAS hits and gut tissue eQTLs",
    "annotate all clinically actionable variants in the NTRK1/2/3 genes",

    # ── Single-cell & spatial ─────────────────────────────────────
    "cluster and annotate cell types in a PBMC single-cell dataset",
    "find trajectory analysis of T-cell differentiation in the tumor microenvironment",
    "search CellxGene for human lung single-cell atlases",
    "what cell types express PD-L1 in the tumor microenvironment?",
    "run cell type annotation on a new scRNA-seq dataset from kidney",
    "find spatial transcriptomics data for human colorectal cancer",
    "cluster spatial spots and identify tissue architecture in liver sections",
    "search for single-cell datasets profiling CAR-T cell products",
    "what cell types are enriched in the stroma of pancreatic cancer?",
    "find scRNA-seq data comparing healthy vs fibrotic lung tissue",
    "identify spatially co-localized cell types in breast tumor sections",
    "search CellxGene for single-cell data on human bone marrow",
    "run pseudotime analysis on developing B-cells from a scRNA-seq experiment",
    "find single-cell datasets for human intestinal organoids",
    "what are the marker genes for exhausted CD8+ T cells in single-cell data?",
    "search for spatial proteomics datasets in melanoma",
    "cluster and annotate a scRNA-seq dataset from human heart tissue",
    "find single-cell multi-omics datasets combining RNA + ATAC",
    "identify rare cell populations in a tumor single-cell dataset",
    "search CellxGene for developmental biology single-cell atlases",

    # ── Epigenomics & methylation ─────────────────────────────────
    "find differentially methylated regions in AML vs normal hematopoietic cells",
    "analyze chromatin accessibility at the MYC locus in lymphoma",
    "search for ChIP-seq data on H3K27me3 in embryonic stem cells",
    "find enhancer regions active in hepatocytes using ATAC-seq data",
    "profile DNA methylation changes during cellular senescence",
    "find super-enhancers driving oncogene expression in neuroblastoma",
    "analyze histone modification patterns at the TP53 promoter in cancer",
    "search for ATAC-seq data comparing naive vs memory T cells",
    "what chromatin states distinguish cancer stem cells from bulk tumor?",
    "find Hi-C data showing 3D genome organization in normal vs leukemic cells",
    "profile methylation patterns at imprinted loci in Beckwith-Wiedemann syndrome",
    "identify regions of chromatin remodeling during macrophage polarization",
    "find epigenomic datasets profiling drug-resistant cancer cell lines",
    "what histone marks define poised enhancers in human islet cells?",
    "analyze DNA methylation age acceleration in different cancer types",

    # ── Proteomics ────────────────────────────────────────────────
    "find differentially expressed proteins in KRAS-mutant vs wild-type CRC",
    "run pathway enrichment on proteomics data from drug-treated cells",
    "search for phosphoproteomics datasets in EGFR-driven lung cancer",
    "what proteins are upregulated in cisplatin-resistant ovarian cancer?",
    "find proteomics data comparing primary tumors vs metastatic sites",
    "identify kinase substrates altered by CDK4/6 inhibitor treatment",
    "search for protein-protein interaction data from AP-MS experiments",
    "what post-translational modifications change during T-cell activation?",
    "find ubiquitinomics data for PROTAC-treated cell lines",
    "compare protein expression across the NCI-60 cell line panel",

    # ── Drug resistance ───────────────────────────────────────────
    "what resistance mechanisms emerge under KRASG12C inhibitor treatment?",
    "find second-site mutations that confer resistance to lorlatinib",
    "how does tumor heterogeneity drive resistance to EGFR TKIs?",
    "search for literature on acquired resistance to ADCs",
    "what pathway reactivation mechanisms drive resistance to BRAF inhibitors?",
    "find resistance mutations to BTK inhibitors in CLL",
    "what non-genetic mechanisms contribute to resistance to targeted therapy?",
    "search PubMed for studies on preventing resistance to CDK4/6 inhibitors",
    "find biomarkers that predict early resistance to immunotherapy",
    "what are the known escape mechanisms from venetoclax in AML?",

    # ── Rare diseases & pediatrics ────────────────────────────────
    "find druggable targets for spinal muscular atrophy beyond SMN",
    "what therapies are in development for Duchenne muscular dystrophy?",
    "search for clinical trials in pediatric high-grade glioma",
    "find genetic targets for Rett syndrome",
    "what's the drug development landscape for cystic fibrosis beyond CFTR modulators?",
    "find targets for Dravet syndrome beyond SCN1A",
    "search PubMed for gene therapy approaches in Gaucher disease",
    "what drugs are being repurposed for Friedreich's ataxia?",
    "find potential targets for familial Mediterranean fever",
    "search for clinical trials in pediatric AML with novel agents",

    # ── Immunology & immuno-oncology ──────────────────────────────
    "profile the immune landscape of TCGA colorectal cancer",
    "find expression patterns of immune checkpoints across solid tumors",
    "what cell types infiltrate pancreatic tumors and correlate with survival?",
    "compare immune scores across cancer types — which are immunologically 'hot'?",
    "find literature on adenosine pathway inhibitors in immuno-oncology",
    "what's the expression profile of LAG-3 across cancer types?",
    "search for scRNA-seq data on myeloid-derived suppressor cells in tumors",
    "find therapeutic targets in the tumor-associated macrophage phenotype",
    "profile the T-cell receptor repertoire diversity in melanoma responders",
    "what's the competitive landscape for CXCR4 antagonists in oncology?",
    "find evidence for CD73 as an immunotherapy target",
    "search PubMed for NK cell-based cancer immunotherapy approaches",
    "what combinations enhance dendritic cell-mediated anti-tumor immunity?",
    "profile cytokine networks in the tumor microenvironment of NSCLC",
    "find targets to overcome T-cell exhaustion in chronic viral infection",

    # ── Metabolism & metabolomics ─────────────────────────────────
    "find metabolic vulnerabilities in IDH1-mutant glioma",
    "what metabolic pathways are rewired in KRAS-driven pancreatic cancer?",
    "search for metabolomics datasets comparing responders vs non-responders to immunotherapy",
    "find druggable targets in the one-carbon metabolism pathway",
    "what metabolic dependencies distinguish cancer stem cells?",
    "profile lipid metabolism changes in steatohepatitis models",
    "find targets in the glutamine addiction pathway of MYC-driven tumors",
    "what metabolic biomarkers predict response to metformin?",
    "search PubMed for ferroptosis as a therapeutic strategy in cancer",
    "find metabolic synthetic lethality with KEAP1 loss in lung cancer",

    # ── Neuroscience targets ──────────────────────────────────────
    "find genetically validated targets for Alzheimer's disease",
    "what's the competitive landscape for TREM2-modulating therapies?",
    "search for clinical trials targeting alpha-synuclein in Parkinson's",
    "find druggable targets for amyotrophic lateral sclerosis",
    "what's the genetic evidence for GBA as a Parkinson's target?",
    "search PubMed for tau propagation inhibitors in clinical development",
    "find targets for treatment-resistant depression beyond monoamines",
    "what's the BBB penetration profile of approved CNS drugs?",
    "search for genetic associations between APOE and treatment response in AD",
    "find novel targets for neuropathic pain beyond ion channels",

    # ── Infectious disease ────────────────────────────────────────
    "find druggable targets in the SARS-CoV-2 replication machinery",
    "what's the competitive landscape for broad-spectrum antivirals?",
    "search PubMed for host-directed therapies against tuberculosis",
    "find targets for drug-resistant Gram-negative bacteria",
    "what repurposing candidates exist for emerging viral threats?",
    "search for clinical trials testing new antibiotics for MRSA",
    "find potential targets in the malaria parasite life cycle",
    "what's the latest pipeline for antifungal drugs?",
    "search PubMed for CRISPR-based antimicrobial strategies",
    "find host targets that broadly restrict respiratory virus replication",

    # ── Fibrosis & inflammation ───────────────────────────────────
    "find genetically supported targets for idiopathic pulmonary fibrosis",
    "what's the competitive landscape for anti-fibrotic therapies?",
    "search for clinical trials in systemic sclerosis with novel agents",
    "find targets linking inflammation and fibrosis in the liver",
    "what's the mechanism of action of nintedanib in IPF?",
    "search PubMed for IL-11 as a fibrosis target",
    "find biomarkers that predict fibrosis progression in NASH",
    "what targets are emerging for cardiac fibrosis?",
    "search for clinical trials targeting TGF-beta in fibrotic diseases",
    "find druggable targets in the senescence-associated secretory phenotype",

    # ── Cardiovascular ────────────────────────────────────────────
    "find genetically validated targets for heart failure",
    "what's the clinical pipeline for RNA-targeting cardiovascular therapies?",
    "search PubMed for ANGPTL3 inhibitors in dyslipidemia",
    "find GWAS targets for atrial fibrillation",
    "what repurposing opportunities exist for approved drugs in heart failure?",
    "find biomarkers for early detection of atherosclerosis",
    "what's the competitive landscape for LP(a)-lowering therapies?",
    "search for targets in the cardiac inflammation pathway post-MI",
    "find genetic evidence linking CETP to cardiovascular outcomes",
    "what novel RNA-based therapies are in development for hypercholesterolemia?",

    # ── Multi-step workflows & complex queries ────────────────────
    "profile lenalidomide end-to-end: chemistry, targets, safety, clinical positioning",
    "validate IDH1 as a target — genetics, expression, druggability, competitive landscape",
    "full compound profile for osimertinib: SAR, ADMET, resistance, combinations",
    "evaluate a PROTAC approach for ER-alpha — feasibility, linker design, safety",
    "comprehensive target assessment for METTL3 in AML — from genetics to clinical",
    "design a lead optimization strategy for a KRASG12D inhibitor series",
    "compare three approaches to targeting MYC: direct binding, synthetic lethality, degradation",
    "build a biomarker strategy for an EZH2 inhibitor Phase II trial",
    "full competitive intelligence report on CDK4/6 inhibitor market",
    "design a drug repurposing screen for ALS using CMap and expression data",
    "evaluate BRD4 as a PROTAC target — structure, degradability, selectivity risks",
    "comprehensive safety assessment for a novel cereblon modulator",
    "compare PPI network, expression, and dependency data for NFE2L2/NRF2",
    "multi-omics integration for discovering biomarkers in triple-negative breast cancer",
    "design an end-to-end screening cascade for a PPI inhibitor program",
    "full landscape analysis: CLDN18.2-targeting strategies in gastric cancer",
    "evaluate allosteric vs orthosteric approaches for targeting SHP2",
    "build an evidence dossier for PRMT5 as an oncology target",
    "design a clinical development plan for a first-in-class TEAD inhibitor",
    "comprehensive analysis of the STING agonist therapeutic landscape",

    # ── RNA therapeutics & gene therapy ───────────────────────────
    "find ASO and siRNA therapies in clinical development for liver diseases",
    "what's the competitive landscape for mRNA therapeutics beyond vaccines?",
    "search PubMed for CRISPR gene editing approaches to sickle cell disease",
    "find targets amenable to antisense oligonucleotide knockdown in CNS",
    "what RNA-targeting modalities are being explored for KRAS?",
    "search for clinical trials using AAV gene therapy in inherited retinal disease",
    "find druggable non-coding RNAs in cancer — lncRNAs and miRNAs",
    "what's the state of base editing therapies for genetic blood disorders?",
    "compare delivery platforms for RNA therapeutics — LNP vs GalNAc vs exosomes",
    "find targets for splice-switching oligonucleotides in neuromuscular diseases",

    # ── Aging & longevity ─────────────────────────────────────────
    "find druggable targets in cellular senescence pathways",
    "what senolytics are in clinical development and for which indications?",
    "search PubMed for rapamycin analogs in aging research",
    "find genetic variants associated with exceptional longevity",
    "what's the evidence for NAD+ boosters in age-related diseases?",
    "profile the senescence-associated secretory phenotype as a drug target space",
    "find clinical trials targeting aging biology directly",
    "what telomere biology targets are being explored therapeutically?",
    "search for epigenetic clock-based endpoints in clinical trials",
    "find repurposing candidates from longevity-associated drug screens",

    # ── Autoimmune & inflammatory ─────────────────────────────────
    "find genetically supported targets for systemic lupus erythematosus",
    "what's the competitive landscape for anti-IL-23 therapies?",
    "search for clinical trials in giant cell arteritis with novel agents",
    "find targets at the intersection of gut barrier integrity and autoimmunity",
    "what's the mechanism of action of approved JAK inhibitors in RA?",
    "compare selectivity profiles of S1P receptor modulators for MS",
    "find biomarkers that predict response to anti-TNF therapy in IBD",
    "search PubMed for regulatory T-cell-based therapies in autoimmunity",
    "what targets are emerging for IgA nephropathy?",
    "find genetic evidence linking TYK2 to multiple autoimmune diseases",

    # ── Oncology — specific tumor types ───────────────────────────
    "what are the top emerging targets in small cell lung cancer?",
    "find actionable molecular subtypes in muscle-invasive bladder cancer",
    "profile the molecular landscape of uveal melanoma",
    "what targets are unique to mesothelioma vs other solid tumors?",
    "find druggable vulnerabilities in TP53-mutant myelodysplastic syndromes",
    "what's the molecular taxonomy of endometrial cancer subtypes?",
    "search for novel targets in dedifferentiated liposarcoma",
    "find the key drivers in anaplastic thyroid cancer",
    "profile the immune and molecular landscape of Merkel cell carcinoma",
    "what targets are being explored for desmoid tumors?",
]
