"""Markdown → shareable HTML report conversion."""

from __future__ import annotations

import html
import re
from datetime import datetime, timezone
from pathlib import Path


def markdown_to_html(md_text: str) -> str:
    """Convert markdown to HTML, falling back to escaped <pre> if markdown is unavailable."""
    try:
        import markdown as md_lib

        return md_lib.markdown(md_text, extensions=["tables", "fenced_code"])
    except ImportError:
        escaped = (
            md_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        )
        return f"<pre>{escaped}</pre>"


def _extract_title(md_text: str, fallback: str = "Report") -> str:
    for line in md_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return fallback


def render_html_report(
    md_text: str,
    *,
    title: str = "Report",
    query: str = "",
) -> str:
    """Render a full HTML document with embedded CSS."""
    body_html = markdown_to_html(md_text)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    safe_title = html.escape(title)
    safe_query = html.escape(query) if query else ""

    query_block = ""
    if query:
        query_block = (
            f'<div class="query-block"><strong>Query:</strong> {safe_query}</div>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{safe_title}</title>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.6;
      max-width: 900px;
      margin: 2rem auto;
      padding: 0 1.5rem;
      color: #1f2937;
    }}
    h1, h2, h3 {{ line-height: 1.25; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
    th, td {{ border: 1px solid #d1d5db; padding: 0.5rem 0.75rem; text-align: left; }}
    pre, code {{ background: #f3f4f6; border-radius: 4px; }}
    pre {{ padding: 1rem; overflow-x: auto; }}
    .meta {{ color: #6b7280; font-size: 0.9rem; margin-bottom: 1.5rem; }}
    .query-block {{
      background: #eff6ff;
      border-left: 4px solid #3b82f6;
      padding: 0.75rem 1rem;
      margin-bottom: 1.5rem;
    }}
    .brand-footer {{
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid #e5e7eb;
      color: #6b7280;
      font-size: 0.85rem;
    }}
  </style>
</head>
<body>
  <div class="meta">Generated {generated_at}</div>
  {query_block}
  {body_html}
  <div class="brand-footer">Generated by CellType</div>
</body>
</html>
"""


def publish_report(md_path: Path, out_path: Path | None = None) -> Path:
    """Convert a markdown file to a shareable HTML page."""
    md_path = Path(md_path)
    if not md_path.exists():
        raise FileNotFoundError(str(md_path))

    md_text = md_path.read_text(encoding="utf-8")
    title = _extract_title(md_text, fallback=md_path.stem)
    html_path = out_path or md_path.with_suffix(".html")
    html_path = Path(html_path)
    html_path.parent.mkdir(parents=True, exist_ok=True)
    html_path.write_text(render_html_report(md_text, title=title), encoding="utf-8")
    return html_path
