"""
Report utility tools for decision-ready communication outputs.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import re

from ct.tools import registry


def _slug(text: str, max_len: int = 64) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", str(text or "").strip().lower()).strip("_")
    return (slug or "pharma_brief")[:max_len]


def _extract_evidence_lines(evidence) -> list[str]:
    lines: list[str] = []
    if evidence is None:
        return lines
    if isinstance(evidence, str):
        for line in evidence.splitlines():
            line = line.strip()
            if line:
                lines.append(line)
        return lines
    if isinstance(evidence, dict):
        if evidence.get("summary"):
            lines.append(str(evidence["summary"]))
        for key in ("key_evidence", "evidence", "findings", "signals"):
            value = evidence.get(key)
            if isinstance(value, list):
                for item in value:
                    lines.append(str(item))
        return lines
    if isinstance(evidence, list):
        for item in evidence:
            if isinstance(item, dict):
                if "summary" in item:
                    lines.append(str(item["summary"]))
                else:
                    lines.append(str(item))
            else:
                lines.append(str(item))
    return [x.strip() for x in lines if str(x).strip()]


@registry.register(
    name="report.pharma_brief",
    description="Generate a one-page pharma decision brief and optionally save as markdown/HTML",
    category="report",
    parameters={
        "query": "Original research question or program objective",
        "program_thesis": "Concise recommendation statement",
        "target_rationale": "Mechanistic rationale (optional)",
        "biomarker_strategy": "Biomarker/patient-selection strategy (optional)",
        "safety_review": "Top liabilities and mitigation strategy (optional)",
        "competitive_differentiation": "Differentiation thesis vs landscape (optional)",
        "evidence": "Optional evidence payload (string/list/dict) to anchor key bullets",
        "save": "Whether to save markdown brief to output directory (default True)",
        "publish_html": "Whether to also publish a shareable HTML page (default True)",
        "filename": "Optional output filename stem",
    },
    usage_guide=(
        "Use at the end of an analysis to create a board/investor/pharma-partner-ready brief "
        "with explicit thesis, risk, and differentiation framing."
    ),
)
def pharma_brief(
    query: str,
    program_thesis: str = "",
    target_rationale: str = "",
    biomarker_strategy: str = "",
    safety_review: str = "",
    competitive_differentiation: str = "",
    evidence=None,
    save: bool = True,
    publish_html: bool = True,
    filename: str = "",
    _session=None,
    **kwargs,
) -> dict:
    """Create a decision-ready pharma brief and optionally persist it."""
    del kwargs
    query = (query or "").strip()
    if not query:
        return {"summary": "query is required.", "error": "missing_query"}

    thesis = (program_thesis or "").strip() or "Recommendation pending deeper evidence synthesis."
    target_rationale = (target_rationale or "").strip() or "Mechanism rationale not yet specified."
    biomarker_strategy = (
        biomarker_strategy or ""
    ).strip() or "Biomarker strategy not yet specified."
    safety_review = (safety_review or "").strip() or "Safety review pending."
    competitive_differentiation = (
        competitive_differentiation or ""
    ).strip() or "Differentiation statement pending competitor benchmarking."

    evidence_lines = _extract_evidence_lines(evidence)[:12]

    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    md_lines = [
        f"# Pharma Brief: {query}",
        "",
        f"*Generated by fastfold-agent-cli on {generated_at}*",
        "",
        "## Program Thesis",
        thesis,
        "",
        "## Target / Mechanism Rationale",
        target_rationale,
        "",
        "## Biomarker / Patient Stratification",
        biomarker_strategy,
        "",
        "## Safety / Liability Review",
        safety_review,
        "",
        "## Competitive Landscape & Differentiation",
        competitive_differentiation,
        "",
        "## Key Evidence Highlights",
    ]

    if evidence_lines:
        for line in evidence_lines:
            md_lines.append(f"- {line}")
    else:
        md_lines.append("- No structured evidence payload provided.")
    md_lines.extend(
        [
            "",
            "## Suggested Next Decisions",
            "1. Confirm go/no-go assumptions with one orthogonal dataset.",
            "2. Define a first-in-human stratification + endpoint strategy.",
            "3. Quantify competitive differentiation against active Phase 2/3 programs.",
        ]
    )
    markdown = "\n".join(md_lines)

    output_md = None
    output_html = None

    if save:
        output_base = None
        if _session is not None and getattr(_session, "config", None) is not None:
            output_base = _session.config.get("sandbox.output_dir")
        out_dir = (
            Path(output_base) / "reports" if output_base else Path.cwd() / "outputs" / "reports"
        )
        out_dir.mkdir(parents=True, exist_ok=True)

        stem = _slug(filename or query)
        output_md = out_dir / f"{stem}_pharma_brief.md"
        counter = 2
        while output_md.exists():
            output_md = out_dir / f"{stem}_pharma_brief_{counter}.md"
            counter += 1
        output_md.write_text(markdown, encoding="utf-8")

        if publish_html:
            from ct.reports.html import publish_report

            output_html = publish_report(output_md)

    summary = (
        f"Generated pharma brief for '{query}'."
        + (f" Saved: {output_md}" if output_md else "")
        + (f" HTML: {output_html}" if output_html else "")
    )

    return {
        "summary": summary,
        "query": query,
        "markdown": markdown,
        "markdown_path": str(output_md) if output_md else None,
        "html_path": str(output_html) if output_html else None,
    }
